###############################################################################
## Config file to store important values related to the hardware components. ##
## ------------------------------------------------------------------------  ##
## Check the official Yahboom G1 Tank expansion board manual for reference   ##
## to all and any pin numbering. ------------------------------------------  ##
###############################################################################

### MOTORS ###
# motor: dictionary of list containing forward,
# ------- back and pwm values associated with
# ------- the correct pin numbers.
motor:
  left_rear: [20, 21, 16] # [forward, back, pwm]
  right_rear: [19, 26, 13] # [forward, back, pwm]

### FAN ###
# fan: dictionary containing pin number and
# ------- whether the fan should be ON/OFF.
fan:
  pin: 2
  enabled: True # True(ON)/False(OFF)

### LED ###
# rgb_led: dictionary containing red, blue
# --------- green led values associated with
# --------- their respective pin numbers.
rgb_led:
  red: 22
  green: 27
  blue: 24

### ULTRASONIC ###
# ultrasonic: dictionary containing echo
# ----------- and trig pin values.
ultrasonic:
  echo: 0 # Connected to SDA (GPIO pin 0)
  trig: 1 # Connected to SDL (GPIO pin 1)
  min_dist: 0.18 # Minimum collision distance
